plugins = []
headers = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "/Users/sivakumarkondapalle/Downloads/Projects/TRADE_BOT/dist"
publishOrigin = "config"
commandOrigin = "config"
command = "npm run build"

[build.environment]
VITE_API_URL = "http://104.155.150.69:8000"

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]